-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 12:45:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Endereco` (
  `idEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `idPessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC) VISIBLE,
  INDEX `fk_Endereco_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `restaurante`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Unidade` (
  `idUnidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeUnidade` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(19) NULL,
  `idEndereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUnidade`),
  UNIQUE INDEX `idUnidade_UNIQUE` (`idUnidade` ASC) VISIBLE,
  INDEX `fk_Unidade_Endereco1_idx` (`idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Unidade_Endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `restaurante`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pessoa` (
  `idPessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoPessoa` ENUM('cliente', 'funcionario', 'gerente') NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `idUnidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_Pessoa_Unidade1_idx` (`idUnidade` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Unidade1`
    FOREIGN KEY (`idUnidade`)
    REFERENCES `restaurante`.`Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pedido` (
  `idPedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPessoa` INT UNSIGNED NOT NULL,
  `descricaoPedido` VARCHAR(100) NOT NULL,
  `observacaoPedido` VARCHAR(60) NULL,
  `valorTotal` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `restaurante`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Item` (
  `idItem` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeItem` VARCHAR(45) NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `preco` DECIMAL(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idItem`),
  UNIQUE INDEX `idItem_UNIQUE` (`idItem` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Estoque` (
  `idEstoque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeEstoque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`),
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`PedidoItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`PedidoItem` (
  `idPedido` INT UNSIGNED NOT NULL,
  `idItem` INT UNSIGNED NOT NULL,
  `quantidadePedido` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPedido`, `idItem`),
  INDEX `fk_Pedido_has_Item_Item1_idx` (`idItem` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Item_Pedido1_idx` (`idPedido` ASC) VISIBLE,
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE,
  UNIQUE INDEX `idItem_UNIQUE` (`idItem` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Item_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `restaurante`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Item_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `restaurante`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`ItemEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`ItemEstoque` (
  `idItem` INT UNSIGNED NOT NULL,
  `idEstoque` INT UNSIGNED NOT NULL,
  `quantidadeTotal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idItem`, `idEstoque`),
  INDEX `fk_Item_has_Estoque_Estoque1_idx` (`idEstoque` ASC) VISIBLE,
  INDEX `fk_Item_has_Estoque_Item1_idx` (`idItem` ASC) VISIBLE,
  UNIQUE INDEX `idItem_UNIQUE` (`idItem` ASC) VISIBLE,
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Item_has_Estoque_Item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `restaurante`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Estoque_Estoque1`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `restaurante`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`UnidadeEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`UnidadeEstoque` (
  `idUnidade` INT UNSIGNED NOT NULL,
  `idEstoque` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUnidade`, `idEstoque`),
  INDEX `fk_Unidade_has_Estoque_Estoque1_idx` (`idEstoque` ASC) VISIBLE,
  INDEX `fk_Unidade_has_Estoque_Unidade1_idx` (`idUnidade` ASC) VISIBLE,
  UNIQUE INDEX `idUnidade_UNIQUE` (`idUnidade` ASC) VISIBLE,
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Unidade_has_Estoque_Unidade1`
    FOREIGN KEY (`idUnidade`)
    REFERENCES `restaurante`.`Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unidade_has_Estoque_Estoque1`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `restaurante`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Telefone` (
  `idTelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoTelefone` ENUM('celular', 'comercial', 'residencial') NOT NULL,
  `numero` INT NOT NULL,
  `idPessoa` INT UNSIGNED NOT NULL,
  `idUnidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTelefone`),
  UNIQUE INDEX `idTelefone_UNIQUE` (`idTelefone` ASC) VISIBLE,
  INDEX `fk_Telefone_Pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_Telefone_Unidade1_idx` (`idUnidade` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `restaurante`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Unidade1`
    FOREIGN KEY (`idUnidade`)
    REFERENCES `restaurante`.`Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pagamento` (
  `idPagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoPagamento` ENUM('dinheiro', 'cartao', 'pix') NOT NULL,
  `idPedido` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC) VISIBLE,
  INDEX `fk_Pagamento_Pedido1_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `restaurante`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
